Projeler/Arac/README.md
=> Recommendify eklendi

KatilimBekleyenler/README.md
=> Katılım bekleyen projeler güncellemesi

projects.json
Serenity logo and website updated.
=> Update projects.json for serenity logo and website

projects.json
Git kullanımını kolaylaştıran, zamandan tasarruf etmenize yardım eden nodejs ve biraz bash komutu ile hazırlanmış araç projelerin arasına eklendi. 👍
=> ✨  g3l projesi eklendi.

projects.json
SSH ile bağlandığımız siteleri kısayol olarak eklemenizi kolaylaştıran bir terminal uygulamasıdır, nodejs ve biraz bash komutu ile hazırlanmıştır.
[l00g.in](https://l00g.in)
=> ✨  l00g.in projesi eklendi.

projects.json
Lazy, açık kaynak kodlu yapay zeka temelli chat botu istemcisidir. 
Servis olarak çalışır,
İyi eğlenceler 👍
=> ✨  lazy.ai eklendi

projects.json
Terminal üzerinden 'kaca ceyrek alirim'/'kaca yuro satarim' gibi sorular ile kur takibi yapabileceğiniz bir cli araci.
=> Kaca ruby gem'i eklendi.

projects.json
Wordpress migration tool eklendi
https://github.com/cagataycali/wordpress-migrate-tool
=> Wordpress migration tool

projects.json
Added university-news-notifier
https://github.com/cagataycali/university-news-notifier
=> Added university-news-notifier

projects.json
Url shortener eklendi
https://github.com/cagataycali/url-shortener
=> Url shortener eklendi

CODE_OF_CONDUCT.md
Daha fazla bilgi için http://contributor-covenant.org
=> Katkıcı Ahdi Topluluk Sözleşmesi eklendi.

projects.json
Lokasyon servisi eklendi,
Lokasyon bazlı uygulamalar için hazırlamış olduğum servis aracılığıyla kendi projenize yakınımdakiler özelliğini katabilirsiniz.
[location-service](https://github.com/cagataycali/location-service)
=> Lokasyon servisi eklendi

projects.json
Kullanımı kolay, minimal ve responsive arayüzler ile mail göndermeye yarayan bir Laravel paketi.
=> Laravel mail template koleksiyonu eklendi

projects.json
Web Arkayuz için eklenen yeni projeler
=> Web Arkayuz Yeni Projeler

projects.json
DiziCLI eklenme talebi oluşturuldu
=> DiziCLI eklenme talebi oluşturuldu

projects.json
=> 4S Eklendi - (Düzeltildi) - 

organizations.json
Organizasyonlara PyIstanbul Eklendi
=> Organizasyonlara PyIstanbul Eklendi

README.md
URL kaynaklı problem düzeltildi.
=> Slack Status Fixed

projects.json
Ders.im öğrencilerin birbirleriyle ders metaryellerini paylaşabilecekleri, geçen senelerde çıkmış sınav sorularını bulabilecekleri, kampüsteki kişilere soru sorabilecekleri sosyal bir platformdur.
%100 açıkkaynak!
=> Ders.im eklendi

projects.json
=> Otağ JavaScript Framework _ Eklendi

projects.json
- `zula` basit bir key-value veritabanı.
- `tdk` ise tdk için yazılmış bir python paketi.
=> 'zula' ve 'tdk' eklendi.

projects.json
Merhaba, 
Projeyi yeni gördüm, elinize sağlık. Katkıcı Ahdi Topluluk Sözleşmesi'ni okudum ve kendi projelerimin de bu platformda bulunmasından mutluluk duyarım.
Açtığım PR şu değişiklikleri içerir:
- projects.json dosyasındaki araçlar bölümüne iki yeni proje eklendi:
- https://github.com/isacikgoz/gitbatch
- https://github.com/isacikgoz/tldr
=> add gitbatch and tldr

projects.json
I've added a new package to project.json file.
=> Add react-native-emoji-dialog to projects.json

projects.json
We have open sourced full of our project and components. 🎉
=> Added NAYN

projects.json
Added Designble's site's repo, the company that used me like a slave.
=> Added malvolent Designble

organizations.json
Added Mercode (mercode.org), non-profit free open source software/OS foundation and social network for developers worldwide.
=> Added Mercode.

projects.json
Coby Browser açık kaynaklı tarayıcı projesi ekleme.
=> Add Coby Browser Browser

projects.json
Replaces Designble user fork with the updated origin.
=> Replace fork with origin

projects.json
Biraz fazla oldu galiba ama :D
=> Add Extum Material Design Theme for Flarum

README.md
- Website URL in `README.md` updated.
=> web site url updated

projects.json
- [Vue Input Spinner](https://github.com/kaangokdemir/vue-input-spinner) added into `projects.json` file.
=> vue input spinner added

projects.json
- [Turkish Id Checker](https://yarnpkg.com/en/package/turkish-id-checker) added into `projects.json` file.
=> turkish id checker added

projects.json
- `vue-pug-snippets` added into `projects.json`
=> Vue pug snippets added

projects.json
https://github.com/f/vue-wait projesi eklendi.
=> vue-wait projesi eklendi

projects.json
https://github.com/muhammederdem/vue-interactive-paycard reposu eklendi.
=> vue-interactive-paycard reposu eklendi.

news.json
https://github.com/acikkaynak/acikkaynak-website/issues/79
=> 'GNOME Community Engagement Challenge 2020' haberini ekle
